[project]
name = "artmipstandardizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2025.9.1",
    "netcdf4>=1.7.2",
    "simplempi>=0.1.5",
    "xarray>=2025.10.1",
]
